database:
  default: # 数据源名称,当不指定数据源时 default 为默认数据源
    type: "mysql" # 数据库类型
    host: "mysql" # 数据库地址
    port: "3306" # 数据库端口
    user: "root" # 数据库用户名
    pass: "123456" # 数据库密码
    name: "cool" # 数据库名称
    charset: "utf8mb4" # 数据库编码
    timezone: "Asia/Shanghai" # 数据库时区
    # debug: true # 是否开启调试模式，开启后会打印SQL日志
    createdAt: "createTime" # 创建时间字段
    updatedAt: "updateTime" # 更新时间字段

redis:
  cool:
    address: "redis:6379"
    db: 0


cool:
  autoMigrate: true
  eps: true
  file:
    mode: "local"
    domain: "http://127.0.0.1:8300"

modules:
  base:
    jwt:
      sso: false
      secret: "chatgpt-share-server"
      token:
        expire: 7200 # 2*3600
        refreshExpire: 1296000 # 24*3600*15
    middleware:
      authority:
        enable: 1
      log:
        enable: 1


# 商城URL 设置你的支付地址之后 前端页面会展示在菜单栏 用户点击弹窗显示
# SHOP_URL: "https://pay.xxx.com"

# mirror 地址
# MIRROR_URL: "https://mirror.xxx.com"

# 限速规则 只用于展示作用，具体限速规则自行配置
SPEED_LIMIT_RULE: "3小时/100次"

# 邮箱服务配置 如果你没有邮箱服务，下面内容删除即可
#emailService:
#  host: "" # SMTP服务器地址
#  port: "" # SMTP端口，使用SSL通常为465
#  user: "" # 邮箱用户名
#  password: "" # 邮箱密码
#  from: "" # 默认发件人地址
#  ssl: true # 是否使用SSL连接（使用端口465通常设置为true）
#  startTLS: true # 跳过证书验证

