database:
  default: # 数据源名称,当不指定数据源时 default 为默认数据源
    type: "mysql" # 数据库类型
    host: "mysql" # 数据库地址
    port: "3306" # 数据库端口
    user: "root" # 数据库用户名
    pass: "123456" # 数据库密码
    name: "cool" # 数据库名称
    charset: "utf8mb4" # 数据库编码
    timezone: "Asia/Shanghai" # 数据库时区
    # debug: true # 是否开启调试模式，开启后会打印SQL日志
    createdAt: "createTime" # 创建时间字段
    updatedAt: "updateTime" # 更新时间字段

redis:
  cool:
    address: "redis:6379"
    db: 0


cool:
  autoMigrate: true
  eps: true
  file:
    mode: "local"
    domain: "http://127.0.0.1:8300"

modules:
  base:
    jwt:
      sso: false
      secret: "chatgpt-share-server"
      token:
        expire: 7200 # 2*3600
        refreshExpire: 1296000 # 24*3600*15
    middleware:
      authority:
        enable: 1
      log:
        enable: 1


# 商城URL 设置你的支付地址之后 前端页面会展示在菜单栏 用户点击弹窗显示
# SHOP_URL: "https://pay.xxx.com"

# mirror 地址
# MIRROR_URL: "https://mirror.xxx.com"

# 限速规则 只用于展示作用，具体限速规则自行配置
SPEED_LIMIT_RULE: "3小时/100次"

# 邮箱服务配置 如果你没有邮箱服务，下面内容删除即可
#emailService:
#  host: "" # SMTP服务器地址
#  port: "" # SMTP端口，使用SSL通常为465
#  user: "" # 邮箱用户名
#  password: "" # 邮箱密码
#  from: "" # 默认发件人地址
#  ssl: true # 是否使用SSL连接（使用端口465通常设置为true）
#  startTLS: true # 跳过证书验证

THEME_TYPE: "1" # 主题类型 1:默认 2:简约

# 内容审核及速率限制
AUDIT_LIMIT_URL: "http://auditlimit:8080/audit_limit"
# 对话响应成功回调地址
ConversationNotifyUrl: "http://auditlimit:8080/audit_limit_callback"


# 自定义 tabs 配置（key 不能做修改，选择需要的配置即可，最少需要填写一个；name 可以任意修改；sort 排序）
# key说明
# 1 -> 免费账号 会查询出所有免费账号显示
# 2 -> 付费账号 会查询出所有付费账号显示
# 3 -> 独享入口（mirror，如果你不用就不管）
# normal -> 3.5账号 会查询出所有3.5账号显示
# advanced -> PLUS账号 会查询出所有PLUS账号显示
# all -> 所有账号 会查询出所有账号显示
tabs:
#  "1":
#    name: "免费节点(10次/24小时)"
#    sort: 0
#  "2":
#    name: "付费节点"
#    sort: 1
#  "3":
#    name: "独享入口"
#    url: "https://ant.design"
#    sort: 2
#    mirror: true
#  "4":
#    name: "嵌套第三方地址"
#    url: "https://baidu.com"
#    sort: 3
#    showIframe: true
#  "5":
#    name: "第三方URL"
#    url: "https://baidu.com"
#    sort: 4
  "normal":
    name: "3.5节点"
    sort: 5
  "advanced":
    name: "PLUS节点"
    sort: 6
#  "all":
#    name: "所有节点"
#    sort: 7
