version: '3.8'
services:
  mysql:
    image: mysql:8.4
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./data/mysql/:/var/lib/mysql/
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai # 指定时区
      MYSQL_ROOT_PASSWORD: "123456" # 配置root用户密码
      MYSQL_DATABASE: "cool" # 业务库名
      MYSQL_USER: "cool" # 业务库用户名
      MYSQL_PASSWORD: "123123" # 业务库密码
  redis:
    image: redis
    # command: --requirepass "12345678" # redis库密码,不需要密码注释本行
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
    volumes:
      - ./data/redis/:/data/
  chatgpt-share-server:
    image: xyhelper/chatgpt-share-server:latest
    restart: always
    ports:
      - 8300:8001
    environment:
      TZ: Asia/Shanghai # 指定时区
      # 接入网关地址
      CHATPROXY: "https://demo.xyhelper.cn"
      # 接入网关的authkey
      AUTHKEY: "xyhelper"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data/chatgpt-share-server/:/app/data/
    labels:
      - "com.centurylinklabs.watchtower.scope=xyhelper-chatgpt-share-server"
  chatgpt-share-server-extend:
    image: fewinter/chatgpt-share-server-extend:latest
    restart: always
    ports:
      - 8301:8002
    environment:
      TZ: Asia/Shanghai
      # 接入网关地址
      CHATPROXY: "https://demo.xyhelper.cn"
      # 接入网关的authkey
      AUTHKEY: "xyhelper"
      # 登录有效期 默认是30天，单位小时
      SESSION_MAX_AGE: 720
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data/chatgpt-share-server/:/app/data/
      - ./extend.js:/app/resource/public/extend.js
    labels:
      - "com.centurylinklabs.watchtower.scope=fewinter-chatgpt-share-server-extend"
    depends_on:
      - chatgpt-share-server
  auditlimit:
    image: fewinter/share-auditlimit-prod
    restart: always
    # ports:
    #   - 9611:8080
    environment:
      LIMIT: 40  # 限制PLUS每个userToken允许的次数
      PER: "3h" # 限制PLUS周期 单位只能是h，0.05h=3分钟，0.1h=6分钟，0.5h=30分钟，1h=60分钟，以此类推

      OLIMIT: 6 # 限制免费模型 每个userToken允许的次数
      OPER: "0.1h" # 限制免费模型周期 单位只能是h，0.05h=3分钟，0.1h=6分钟，0.5h=30分钟，1h=60分钟，以此类推

      O1LIMIT: 50 # 限制PLUS每个userToken允许O1的次数
      O1PER: "1d" # 限制周期 1h=1小时，1d=一天，1w=一周，1y=一年

      O1MINILIMIT: 50 # 限制PLUS每个userToken允许O1mini的次数
      O1MINIPER: "1d" # 限制周期 1h=1小时，1d=一天，1w=一周，1y=一年
    volumes:
      - ./config.yaml:/app/config.yaml
      # 如果不需要内容审核填加一个keywords.txt文件，内容为空，再把下面的注释打开即可
      #- ./keywords.txt:/app/data/keywords.txt
    labels:
      - "com.centurylinklabs.watchtower.scope=fewinter-chatgpt-share-server-extend"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope xyhelper-chatgpt-share-server,fewinter-chatgpt-share-server-extend --cleanup
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - WATCHTOWER_POLL_INTERVAL=86400  # 设置为每24小时检查一次
    labels:
      - "com.centurylinklabs.watchtower.scope=xyhelper-chatgpt-share-server"
