version: '3.8'
services:
  mysql:
    image: mysql:8.4
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./data/mysql/:/var/lib/mysql/
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai # 指定时区
      MYSQL_ROOT_PASSWORD: "123456" # 配置root用户密码
      MYSQL_DATABASE: "cool" # 业务库名
      MYSQL_USER: "cool" # 业务库用户名
      MYSQL_PASSWORD: "123123" # 业务库密码
  redis:
    image: redis
    # command: --requirepass "12345678" # redis库密码,不需要密码注释本行
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
    volumes:
      - ./data/redis/:/data/
  chatgpt-share-server:
    image: xyhelper/chatgpt-share-server:latest
    restart: always
    ports:
      - 127.0.0.1:8300:8001
    environment:
      TZ: Asia/Shanghai # 指定时区
      # 接入网关地址
      CHATPROXY: "https://demo.xyhelper.cn"
      # 接入网关的authkey
      AUTHKEY: "xyhelper"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data/chatgpt-share-server/:/app/data/
    labels:
      - "com.centurylinklabs.watchtower.scope=xyhelper-chatgpt-share-server"
  chatgpt-share-server-extend:
    image: fewinter/chatgpt-share-server-extend:latest
    restart: always
    ports:
      - 127.0.0.1:8301:8002
    environment:
      TZ: Asia/Shanghai
      # 接入网关地址
      CHATPROXY: "https://demo.xyhelper.cn"
      # 接入网关的authkey
      AUTHKEY: "xyhelper"
      # 登录有效期 默认是30天，单位小时
      SESSION_MAX_AGE: 210
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data/chatgpt-share-server/:/app/data/
      - ./extend.js:/app/resource/public/extend.js
    labels:
      - "com.centurylinklabs.watchtower.scope=fewinter-chatgpt-share-server-extend"
    depends_on:
      - chatgpt-share-server
  auditlimit:
    image: fewinter/share-auditlimit-prod
    restart: always
    # ports:
    #   - 9611:8080
    environment:
      # 免费用户 沿用之前的配置
      OLIMIT: 20 # 限制免费模型 每个userToken允许的次数
      OPER: "3h" # 限制免费模型 周期1h, 1d, 1w, 1y
      
      # 模型限制 （注意：模型名称要大写，后面跟的是次数/时间）
      AUTO: "200/3h"
      TEXT-DAVINCI-002-RENDER-SHA: "200/3h"
      GPT-4O-MINI: "200/3h"
      GPT-4O: "60/3h"
      GPT-4: "20/3h"
      GPT-4O-CANMORE: "30/3h"
      O1: "20/24h"
      O1-PRO: "20/24h"
      O3: "20/24h"
      O4-MINI: "60/3h"
      O4-MINI-HIGH: "60/3h"

    volumes:
      - ./config.yaml:/app/config.yaml
      # 如果不需要内容审核填加一个keywords.txt文件，内容为空，再把下面的注释打开即可
      #- ./keywords.txt:/app/data/keywords.txt
    labels:
      - "com.centurylinklabs.watchtower.scope=fewinter-chatgpt-share-server-extend"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope xyhelper-chatgpt-share-server,fewinter-chatgpt-share-server-extend --cleanup
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - WATCHTOWER_POLL_INTERVAL=86400  # 设置为每24小时检查一次
    labels:
      - "com.centurylinklabs.watchtower.scope=xyhelper-chatgpt-share-server"
